EclipseFdn/hugo-solstice-theme

- layouts/partials/header.html
Signed-off-by: Stephanie Swart <stephanie.swart@eclipse-foundation.org>
> Removed Welcome , from top of page

- .travis.yml
> remove fonts, css and js from deploy

- exampleSite/config.toml
- layouts/partials/footer.html
- layouts/partials/google_tag_manager.html
- layouts/partials/head.html
- package-lock.json
- package.json
- webpack.mix.js
> Add google tag manager

- package.json
- webpack.mix.js
> Update theme to latest version

- layouts/partials/nav_more.html
> #17 - Add Learn More link to the More menu

- layouts/_default/section.html
> Add pagination to section template file

- layouts/shortcodes/youtube.html
> Update the youtube shortcode

- layouts/shortcodes/youtube.html
> fix youtube videos on https

- layouts/partials/footer.html
> Remove extra closing tags in footer

- .travis.yml
- package-lock.json
- package.json
> prepare new release

- exampleSite/layouts/partials/sidebar.html
- layouts/_default/home.html
> use relURL

- data/events.yml
- exampleSite/config.toml
- layouts/_default/home.html
- layouts/partials/events.html
- theme.toml
> Add an events section

- layouts/meeting_minutes/section.html
> Add meeting minutes layout

- exampleSite/config.toml
- exampleSite/content/meeting_minutes/_index.md
- exampleSite/data/events.yml
- exampleSite/data/meeting_minutes/example.yml
- layouts/meeting_minutes/list.html
> update example site

- layouts/partials/footer.html
> add Report a Vulnerability link

- exampleSite/content/news/example1.md
- exampleSite/content/news/example2.md
- layouts/_default/summary.html
- layouts/partials/head.html
> Redirect content items

- exampleSite/content/membership/members/_index.md
- layouts/membership/summary.html
- layouts/shortcodes/members_list.html
> #33 - Improve the Explore Members page

- exampleSite/data/meeting_minutes.yml
- layouts/shortcodes/meeting_minutes.html
> #42 - Use tabs to display the meeting minutes

- exampleSite/config.toml
- exampleSite/content/faq/_index.md
- exampleSite/content/faq/faq_1.md
- exampleSite/content/faq/faq_2.md
- layouts/faq/list.html
> #36 - Add FAQ page

- layouts/shortcodes/events.html
> Fix the Events sorting by expiry date

- exampleSite/config.toml
- exampleSite/content/_index.md
- exampleSite/content/components/featured_footer.md
- exampleSite/content/components/featured_story.md
- exampleSite/data/featuredstory.yml
- layouts/_default/baseof.html
- layouts/partials/featured_footer.html
- layouts/partials/featured_story.html
Progress on creating footer + story features for hugo theme.
Change-Id: Ib26d16491e42951deaeb6fd9a98cd5742604f642
> Create a Featured footer/story component #24

- package-lock.json
- package.json
> Update solstice-assets to 0.0.54

- layouts/_default/list.html
- layouts/_default/summary.html
> Use .Render in default list

- exampleSite/layouts/partials/sidebar.html
Change-Id: Ie11fd7f0211fe3152e1b3e7c6a63ee6d2c9ad3a6
> Improvements to documentation exampleSite #54

- exampleSite/config.toml
- exampleSite/content/components/project_list.md
- exampleSite/content/projects/_index.md
- exampleSite/content/projects/example-1/index.md
- exampleSite/content/projects/example-2/index.md
- layouts/projects/single.html
- layouts/projects/summary.html
- package-lock.json
- package.json
Change-Id: I7ef3034465bbd62b5b5a9d25380dafb696b8797c
> Create a project list component #34

- exampleSite/content/components/project_list.md
- exampleSite/layouts/partials/sidebar.html
Change-Id: Ibc3c0fe590e6de0c2c6cc21d7f0c527dba205124
> Fix for component URLs + project list example page

- layouts/partials/footer.html
Change-Id: I283e503bd5402e43d256637e600c5f3c544bd25b
> Removed Google+ from footer links

- layouts/partials/navbar.html
Change-Id: I682236f6b2b39f8e7e5f57e7e8bbbbfe817f4cb7
> Added optional params for header navbar

- layouts/partials/navbar.html
New param available `navbar_wrapper_classes` in site config.
Change-Id: I914e59342ec4e73fbc84f0411bab7fde2741f84e
> Added wrapper around navbar, with default class target

- layouts/partials/featured_story.html
> Fix featured story

- layouts/shortcodes/members_list.html
> Improve members list shortcode

- .travis.yml
- package.json
> fix dependency issue

- .travis.yml
- package-lock.json
- package.json
> fix build issue with less

- layouts/_default/baseof.html
- layouts/partials/featured_footer.html
- layouts/partials/featured_story.html
- package-lock.json
- package.json
> Improve featured story and footer

- layouts/partials/navbar.html
> allow users to alter cfa classes

- layouts/partials/navbar.html
> allow alter class on menu with cfa

- layouts/partials/navbar.html
> allow more flexibility with the width of cfa

- exampleSite/data/site_params.yml
- layouts/partials/breadcrumbs.html
- layouts/partials/footer.html
Change-Id: Ie9fdd695b1adadefe5fe061b4363ab810c3059f6
> Fixed breadcrumbs + added params for footer links

- exampleSite/config.toml
- exampleSite/content/_index.fr.md
- exampleSite/content/single_page/index.fr.md
- i18n/en.toml
- layouts/partials/footer.html
- layouts/partials/nav_toggle.html
- layouts/partials/navbar.html
> Added language selector support in header

- layouts/shortcodes/members_list.html
> Added data file support for members list

- layouts/_default/summary.html
- layouts/faq/list.html
- layouts/partials/breadcrumbs.html
- layouts/partials/head.html
- layouts/partials/jumbotron.html
- layouts/partials/main_prefix.html
- layouts/shortcodes/members_list.html
> Update to template files to allow HTML in headers

- i18n/en.toml
- layouts/404.html
- layouts/faq/list.html
- layouts/partials/breadcrumbs.html
- layouts/partials/google_search.html
- layouts/partials/header.html
- layouts/partials/nav_more.html
- layouts/partials/nav_toggle.html
- layouts/projects/single.html
- layouts/projects/summary.html
- layouts/shortcodes/events_table.html
- layouts/shortcodes/members_list.html
- layouts/shortcodes/taxonomy_list.html
> I18N updates for base theme

- theme.toml
> add static/mix.js to ingoreFiles

- exampleSite/config.toml
- exampleSite/content/components/agenda.md
- exampleSite/data/en/2019/agenda.yml
- exampleSite/data/en/active/agenda.yml
- exampleSite/data/en/agenda.yml
- exampleSite/data/en/no_types/agenda.yml
- exampleSite/data/en/slides/agenda.yml
- exampleSite/data/fr/agenda.yml
- i18n/en.toml
- layouts/shortcodes/agenda.html
- package-lock.json
- package.json
Created agenda component based on a mix of Jakartaone and OSDForum with
multiple examples and instructions on component page.
> Create an agenda component based on the OSDForum and JakartaOne...#84

- layouts/partials/nav_toggle.html
- netlify.toml
> fix mobile menu

- i18n/en.toml
- layouts/shortcodes/eclipsefdn_project_list.html
> Fixed read more text to have different text for sighted/non users

- .travis.yml
- netlify.toml
- package.json
> create fetch project script

- exampleSite/config.toml
- exampleSite/content/components/eclipsefdn_projects.md
- layouts/shortcodes/eclipsefdn_project_list.html
> add working_group params with eclipsefdn_project_list

- NOTICE.md
- layouts/shortcodes/figure.html
> Added override to figure shortcode

- layouts/shortcodes/eclipsefdn_project_list.html
> replace scope with summary

- layouts/partials/breadcrumbs.html
- layouts/partials/head.html
- layouts/partials/jumbotron.html
- layouts/partials/main_prefix.html
This should address the title case issue on edgenative.eclipse.org:
https://github.com/EclipseFdn/edgenative.eclipse.org/issues/9#issuecomment-565076102
> use title case for titles

- layouts/shortcodes/members_list.html
> Updated members list to properly capture links

- layouts/_default/summary.html
> Added additional check to use link param for summary item links

- layouts/partials/featured_footer.html
- layouts/partials/featured_story.html
> Featured footer/story fails when there are no defined stories on... #112

- exampleSite/data/site_params.yml
- layouts/partials/featured_footer.html
- layouts/partials/featured_story.html
- layouts/partials/jumbotron.html
- layouts/partials/main_prefix.html
- layouts/partials/main_suffix.html
Featured footer/story fails when there are no defined stories on site
#112
> add new params to add flexibility to theme

- exampleSite/data/featuredstory.yml
- layouts/partials/featured_footer.html
- layouts/partials/featured_story.html
Added new post_content field that is inserted between content and link.
Added new post_class, content_class, preamble_class, and header_class
fields that inject classes on the given fields.
> Update featured story/footer for new layouts

- layouts/partials/head.html
> Add aternative to SEO title suffix

- exampleSite/config.toml
- exampleSite/content/components/registration.md
- exampleSite/content/components/user_bios.md
- exampleSite/content/components/user_display.md
- exampleSite/content/single_page/user_bios.md
- exampleSite/data/en/2019/registration.yml
- exampleSite/data/en/2019/speakers.yml
- exampleSite/data/en/2019/user.yml
- exampleSite/data/en/agenda.yml
- exampleSite/data/en/default/registration.yml
- exampleSite/data/en/default/user.yml
- exampleSite/data/en/expired_event/registration.yml
- i18n/en.toml
- layouts/partials/footer.html
- layouts/shortcodes/agenda.html
- layouts/shortcodes/registration.html
- layouts/shortcodes/user_bios.html
- layouts/shortcodes/user_display.html
- package-lock.json
- package.json
- webpack.mix.js
Added registration, users display, and users bio components. Updated
agenda to have abstract functionality. These components make up the core
of base events implementation and template.
> Integrate event functionality from JakartaOne into base... #119

- layouts/partials/featured_footer.html
- layouts/partials/featured_story.html
Change-Id: Ib09d4827065101f57f36e74c8116e280fe952681
> fix js with featured stories

- exampleSite/content/components/sponsors.md
- exampleSite/data/en/2020/default/sponsors.yml
- exampleSite/data/en/2020/sample/sponsors.yml
- exampleSite/data/en/default/sponsors.yml
- exampleSite/data/en/sample/sponsors.yml
- i18n/en.toml
- layouts/shortcodes/sponsors.html
> Add sponsors component for use with event pages #119

- exampleSite/content/components/registration.md
- layouts/shortcodes/registration.html
> Fix container-fluid check in registration shortcode #119

- exampleSite/data/featuredstory.yml
- layouts/partials/featured_footer.html
- layouts/partials/featured_story.html
> Updated featured story filters to take start date into account

- exampleSite/content/components/agenda.md
- i18n/en.toml
- layouts/shortcodes/bootstrap/modal.html
- layouts/shortcodes/events/agenda.html
- layouts/shortcodes/events/registration.html
- layouts/shortcodes/events/sponsors.html
- layouts/shortcodes/events/user_bios.html
- layouts/shortcodes/events/user_display.html
- layouts/shortcodes/grid/div.html
- layouts/shortcodes/grid/section-container.html
- layouts/shortcodes/section-wrapper.html
- package-lock.json
- package.json
Removing last div.row in grid/section-container in an effort to
standardize how we build our shortcodes.
div.row is only needed with div.col-. 
We should be including div.row in our shortcodes only when we are using div.col-.
> adding div shortcode

- layouts/partials/nav_toggle.html
Fix #134
Change-Id: Ic54c2f0e883edd95808d02650dba250bc083adbb
> Example site does not render with Hugohugo v0.71.1

- layouts/partials/featured_story.html
> Update featured story ad class

- layouts/shortcodes/figure.html
> Added image class (imgClass) parameter to figure shortcode

- layouts/shortcodes/events/user_display.html
Change-Id: I303a4a3ac4313a425d6a5ff9b2eaac86ea04ad44
> Make the learn more optional

- layouts/shortcodes/events/sponsors.html
Fix #141
Change-Id: I88950a4a72e4684b565bf1be6b188572f7236b56
> Add "Become a Sponsor" button to event/ sponsors component #141

- exampleSite/config.toml
- layouts/partials/nav.html
> Added support for nested menus in drop down main menu

- exampleSite/content/components/agenda.md
- exampleSite/data/en/multistream/agenda.yml
- layouts/shortcodes/events/agenda.html
> Update the Events/Agenda shortcode to allow for multiple agenda...#145

- exampleSite/data/en/active/agenda.yml
- layouts/shortcodes/events/agenda.html
> Add support for HTML in presenter field to support links

- layouts/shortcodes/events/user_display.html
> Add option to configure item class for non-carousel items

- layouts/partials/footer.html
- layouts/partials/socials.html
Split out social links into partial that can be overridden on a site
level basis.
Fixes #158
> Extract footer social media links to new partial/shortcode for... #158

- layouts/partials/featured_footer.html
- layouts/partials/featured_story.html
> Featured story is broken in IE 11

- exampleSite/config/_default/languages.toml
- exampleSite/config/_default/menus.zh.toml
- exampleSite/content/_index.zh.md
- i18n/zh.toml
Signed-off-by: laliwa <40311795@qq.com>
> fix footer about foundation etc.

- README.md
- exampleSite/content/components/agenda.md
- exampleSite/data/en/2020/sample/agenda.yml
- exampleSite/data/en/active/agenda.yml
- exampleSite/data/en/default/agenda.yml
- exampleSite/data/en/slides/agenda.yml
- layouts/shortcodes/events/agenda.html
Fix #166 
This is found from https://github.com/openhwgroup/osdforum.org/pull/98#
> fix showing play when no vod is set and add readme to get started

- layouts/_default/baseof.html
- layouts/partials/featured_footer.html
- layouts/partials/featured_story.html
> Featured footer should be before the footer

- exampleSite/content/_index.md
- webpack.mix.js
> try to rebuild

- layouts/shortcodes/eclipsefdn_project_list.html
> fix website url in eclipsefdn_project_list.html

- exampleSite/config/_default/menus.en.toml
- exampleSite/content/hide_call_for_action/_index.md
- layouts/partials/navbar.html
In order to fix https://github.com/jakartaee/jakarta.ee/issues/920#issuecomment-725605496
> add page param to hide call for action button and add example

- exampleSite/content/components/agenda.md
- exampleSite/data/en/default/agenda.yml
- layouts/shortcodes/events/agenda.html
> Update to move agenda body outside of anchor

- netlify.toml
> update node version in netlify

- exampleSite/content/components/agenda.md
- exampleSite/data/en/default/agenda.yml
- i18n/en.toml
- i18n/es.toml
- i18n/jp.toml
- i18n/pt.toml
- layouts/shortcodes/events/agenda.html
- package-lock.json
- package.json
Fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=568731
Let's wait until Jan 12 to make these changes live. I will make this ready on Jan 11.
> Bug 568731 - update footer copyright text

- exampleSite/config/_default/languages.toml
- exampleSite/config/_default/menus.ru.toml
- exampleSite/content/_index.ru.md
- i18n/ru.toml
> Add russian

- exampleSite/config/_default/menus.en.toml
- exampleSite/config/_default/menus.es.toml
- exampleSite/config/_default/menus.fr.toml
- exampleSite/config/_default/menus.jp.toml
- exampleSite/config/_default/menus.pt.toml
- exampleSite/config/_default/menus.zh.toml
- exampleSite/content/translations.md
Add page documenting how translations should be handled for new languages within the Hugo solstice theme.
> Define and explain translations in our Event Website Content... #172

- exampleSite/config/_default/menus.en.toml
- exampleSite/config/_default/menus.es.toml
- exampleSite/config/_default/menus.fr.toml
- exampleSite/config/_default/menus.jp.toml
- exampleSite/config/_default/menus.pt.toml
- exampleSite/config/_default/menus.ru.toml
- exampleSite/config/_default/menus.zh.toml
Fix sample site menu translations to be in sync.
> Small issue, some menu items of other languages are missing #207

- bin/i18nChecker.js
- i18n/tr.toml
- i18n/zh.toml
- package-lock.json
- package.json
Revert 4 keys in zh/tr to remove brand misuse. Added script to help determine issues with translation files beyond what is provided by default.
> Review translations for errors/brand misuse #225

- exampleSite/content/components/cards.md
- exampleSite/data/en/cards.yml
- exampleSite/data/en/cards_branding.yml
- exampleSite/data/en/cards_mixed.yml
- exampleSite/data/en/cards_sample.yml
- layouts/shortcodes/cards.html
- package-lock.json
- package.json
- static/js/eclipsefdn.adopters.js
- static/js/solstice.hugo.js
- webpack.mix.js
Currently using PR to show output on the page
> Added cards component

- layouts/partials/footer_js.html
- layouts/shortcodes/eclipsefdn_adopters.html
> fix adopters
