EclipseFdn/hugo-solstice-theme

- exampleSite/config.toml
- exampleSite/content/_index.md
- exampleSite/content/components/_index.md
- exampleSite/content/components/faq.md
- exampleSite/content/components/index.md
- exampleSite/data/doc_params.yml
- exampleSite/data/site_params.yml
- exampleSite/layouts/_default/index.html
- exampleSite/layouts/components/list.html
- exampleSite/layouts/partials/param_list.html
- exampleSite/layouts/partials/sidebar.html
Updated site to add document + site parameters, and rearrange the
component samples into a styleguide.
Change-Id: Ib13a25251c00d94f8b97eba25d673d9973d021df
> Document parameters in README.md #32

- layouts/partials/navbar.html
Added check around mobile nav menu to only print if there are no
elements in the main site menu.
Change-Id: I97dd894de3e4fa041d4219d0784ef399a97f96c9
> Hamburger menu should be hidden on mobile if there are no nav... #66

- exampleSite/config.toml
- exampleSite/content/components/tables.md
- layouts/partials/footer.html
- layouts/partials/head.html
- layouts/partials/head_variables.html
- webpack.mix.js
Added table injection logic to a new JS file called hugo-custom.js,
created by an updated webpack file. The logic was added to the footer
after solstice injection (to ensure Bootstrap is loaded) in a new
footer_hugo partial. Variables for the table injection are set within
the head to be used in the page.
Change-Id: Ib99d75ded1caaf58241771bcefa176543016d68f
> Fix HTML tables #68

- layouts/partials/navbar.html
Switch isset usage in navbar mobile menu check to use simple
comparisons, as 'isset' is not supported for menus in versions 54 and
earlier.
Change-Id: I485cc874d88d32f13ac33b82c9d6e707b17515bb
> Fix navbar for versions of hugo < v 0.55

- exampleSite/config.toml
- exampleSite/content/downloads/_index.md
- exampleSite/data/site_params.yml
- layouts/partials/navbar.html
Added `hide_cfa_same_page` site param to hide CFA links on page of.
Change-Id: If1376cfd2dea3b26630e1f38248482486d92ba95
> Added ability to hide CTA on page of link via site param

- .travis.yml
- README.md
- exampleSite/content/components/tables.md
- exampleSite/data/featuredstory.yml
- i18n/en.toml
Updated some broken i18n values in newer versions, added note about
custom HTML in content files as a known issue. Updated a featured story
to be available in perpetuity.
> Update to support hugo 0.62.2

- layouts/partials/jumbotron.html
> Fix ordering of title + safeHTML on jumbotron header

- exampleSite/content/components/agenda.md
- exampleSite/content/components/registration.md
- exampleSite/content/components/user_display.md
- layouts/shortcodes/agenda.html
- layouts/shortcodes/registration.html
- layouts/shortcodes/user_display.html
Updated registration, agenda, and user_display to enable automatic
detection of container-fluid being set. Removed the 'banner' attribute.
Added a named param for container class to the registration,
user_display, and agenda components.
> Fixed container-fluid banner examples to use proper class for detection

- layouts/shortcodes/events/agenda.html
- layouts/shortcodes/events/registration.html
- layouts/shortcodes/events/user_display.html
Changes found while migrating jakartaone that required tweaks to carry
over. Added imageroot and image classes to user carousel images, fixed
registration classees to properly render with images, and made the event
ID handling consistent in the agenda.
> Tweaks to events generic templates to increase flexibility

- layouts/shortcodes/bootstrap/button.html
- layouts/shortcodes/members_list.html
Fixed sorting on members list to be insensitive alphabetical order
rather than case sensitive. Added button shortcode to insert buttons
into page files without templates.
> Added fixes needed for openPASS content update

- layouts/shortcodes/events/agenda.html
- layouts/shortcodes/events/registration.html
- layouts/shortcodes/events/sponsors.html
Added header class optional parameter for event registration. Updated
sponsors image list to be a list instead of divs with columns. Added
optional list for presenters.
> Tweaks to events framework for OSDForum

- layouts/partials/head_custom.html
Roboto is now our default font.
> Remove libre franklin from base theme

- exampleSite/config/_default/config.toml
- layouts/partials/google_tag_manager.html
- layouts/partials/google_tag_manager_no_script.html
- layouts/partials/header.html
The noscript is required to validate the site with google search
console.
> add google analytics no script

- debug.log
- layouts/partials/footer.html
- layouts/partials/nav_toggle.html
- layouts/partials/navbar.html
To be able to add params to custom footer instead of {{ define footer }} for https://github.com/jakartaee/jakarta.ee/pull/929
And also add the ability to customize the page logo in navbar and mobile nav  instead of {{ define navbar }} 
It's a combine with https://github.com/EclipseFdn/solstice-assets/pull/184
> add params to custom footer class name and navbar logo

- exampleSite/config/_default/config.toml
- exampleSite/config/_default/menus.en.toml
- exampleSite/content/without_breadcrumb/_index.md
- exampleSite/data/site_params.yml
- layouts/_default/baseof.html
According to the requests from Philippe for https://github.com/EclipseFdn/opensourceinnovation.eu, I add this option in Confilg to disable breadcrumb for all pages.
> option to disable all breadcrumb

- i18n/en.toml
This is caught by https://github.com/EclipseFdn/ecdtools.eclipse.org/pull/73#issuecomment-734268756
> Use plural of table of contents for FAQ

- exampleSite/content/components/agenda.md
- exampleSite/data/en/multistream/agenda.yml
- layouts/shortcodes/events/agenda.html
Part of https://github.com/EclipseFdn/hugo-solstice-theme/issues/188
For Hugo theme, the example agenda does not have long titles(And the current font-size is already small-14px), I'm thinking of adding font-size small when mobile view to events page separately (https://github.com/EclipseFdn/events.eclipse.org/pull/160).
I'm not adding the font size in `.eclipsefdn-agenda { table { } }` in solstice-assets is because it will be different due to different situations in the specific sites. On Hugo theme and Osdforum, 14px would be good, while for events, it needs to be 12px. 
wdyt?
> Remove agenda tab table spacing on mobile

- exampleSite/config/_default/languages.toml
According to https://github.com/jakartaee/jakartaone.org/issues/250, we should use Русский for Russian language switcher. 
> Update Russian Language Switch

- exampleSite/config/_default/menus.en.toml
- exampleSite/content/components/text_target.md
- layouts/shortcodes/text_target.html
> Add text target component

- exampleSite/config/_default/menus.en.toml
- exampleSite/content/custom-jumbotron/_index.md
- exampleSite/data/doc_params.yml
- exampleSite/data/site_params.yml
- layouts/partials/jumbotron.html
This is inspired by https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/96#issuecomment-794110285
An example will be https://deploy-preview-206--eclipsefdn-hugo-solstice-theme.netlify.app/custom-jumbotron/
> Add custom jumbotron params

- exampleSite/content/components/list_wrapper.md
- layouts/shortcodes/html/li.html
- layouts/shortcodes/html/list_wrapper.html
> Add custom list implementation along with notes for raw HTML lists

- .travis.yml
- README.md
- netlify.toml
- package-lock.json
- package.json
> compile css/js on npm install step

- layouts/partials/footer.html
- layouts/partials/head.html
- layouts/partials/nav_toggle.html
- layouts/partials/navbar.html
- layouts/shortcodes/eclipsefdn_adopters.html
I found that testing locally is difficult when having an absolute URL for the stylesheet. 
Therefore I change this to a relative URL. The same of other occurrences in the file that should work with relative URLs as well. 
If someone puts an absolute URL there (for example the default URL), Hugo will still output the absolute URL if the host name is different from the hostname of the site. 
Please let me know there have been reasons to have this absolute. 
As this is only for testing locally, there is no need to hurry for a release.
> Use relative URLs for better preview when testing locally

- i18n/tr.toml
This pull request was made to contribute to the website prepared for JakartaOne Livestream Turkish. Details: https://github.com/jakartaee/jakartaone.org/issues/279
> Contribution for Turkish website

- layouts/projects/single.html
- layouts/projects/summary.html
We used the project list on the AsciiDoc WG page and changed the following items that might be interesting for other projects as well. Therefore I create this pull request. If something shouldn't be added to the theme, please let me know and I'll remove it from the PR.
Live view (include also some other minor changes like removing the tags in the single project view): 
https://eclipsefdn-asciidoc-wg.netlify.app/projects/ 
Single Project View:
* add link to project as "call to action"
Project Summary View:
* start with a dotted line as the list also ends with a dotted line
* show incubating logo for incubating projects like on the single project view
* show link to website when there is no download link
There is no need to rush here, we've duplicated the templates in the WG for now.
> improved handling for incubating projects

- exampleSite/content/components/agenda.md
- exampleSite/data/en/active/agenda.yml
- exampleSite/data/en/slides/agenda.yml
- layouts/shortcodes/events/agenda.html
For issue220: https://github.com/EclipseFdn/hugo-solstice-theme/issues/220 
Also fixed a tiny issue. 
The demo agenda, Custom Tile section, targeted at default yaml file (agenda.yaml) which should be day_2.yaml file.
> Added multi-time support

- layouts/_default/baseof.html
- layouts/partials/footer.html
- layouts/partials/footer_js.html
- layouts/partials/footer_links/footer-copyright.html
- layouts/partials/footer_links/footer-eclipse-foundation.html
- layouts/partials/footer_links/footer-legal.html
- layouts/partials/footer_links/footer-other.html
- layouts/partials/footer_links/footer-useful-links.html
- layouts/partials/footer_links/links.html
> add flexibility to footer

- layouts/partials/jumbotron.html
For Infra-4243 and [PR71](https://github.com/EclipseFdn/asciidoc-wg.eclipse.org/pull/71)
> Added safeHTML in tagline

- layouts/partials/header.html
- layouts/partials/navbar.html
- layouts/partials/toolbar.html
> short code for toolbar

- exampleSite/config/_default/menus.en.toml
- exampleSite/config/_default/menus.es.toml
- exampleSite/config/_default/menus.fr.toml
- exampleSite/config/_default/menus.jp.toml
- exampleSite/config/_default/menus.pt.toml
- exampleSite/config/_default/menus.ru.toml
- exampleSite/config/_default/menus.zh.toml
- exampleSite/content/coming-soon/_index.md
- layouts/coming-soon/coming-soon.html
- layouts/partials/coming-soon-header.html
- package.json
- yarn.lock
> [mbo] - add coming soon to base theme
